CREATE DATABASE PIZZAS;
--TABLE OF ORDERS
DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY,
	DATE DATE ,
	TIME TIME
); 
--TABLE OF PIZZA_TYPES
CREATE TABLE PIZZA_TYPES(
	PIZZA_TYPE_ID VARCHAR(50) PRIMARY KEY,
	NAME VARCHAR(100),
	CATEGORY VARCHAR(50),
	INGREDIENTS TEXT 
);
--TABLE OF PIZZAS
CREATE TABLE PIZZAS(
	PIZZA_ID VARCHAR(50) PRIMARY KEY,
	PIZZA_TYPE_ID VARCHAR(50),
	P_SIZE VARCHAR(5),
	PRICE DECIMAL(5,2),
	FOREIGN KEY (PIZZA_TYPE_ID)
		REFERENCES PIZZA_TYPES(PIZZA_TYPE_ID)
);
--TABLE OF ORDER_DETAILS
CREATE TABLE ORDER_DETAILS(
	ORDER_DETAILS_ID INT PRIMARY KEY,
	ORDER_ID INT ,
	PIZZA_ID VARCHAR(50),
	QUANTITY INT ,
	FOREIGN KEY (ORDER_ID)
		REFERENCES ORDERS(ORDER_ID),
	FOREIGN KEY(PIZZA_ID)
		REFERENCES PIZZAS(PIZZA_ID)
);

SELECT * FROM PIZZA_TYPES;
SELECT * FROM PIZZAS;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_DETAILS;
-- QUERYS 
--1. Retrieve all orders.
SELECT * FROM ORDERS;
--2. Count the total number of orders.
SELECT COUNT(*) AS TOTAL_ORDER FROM ORDERS;
--3. Find the total number of pizzas sold.
SELECT SUM(QUANTITY) AS NO_OF_PIZZA_SOLD FROM  ORDER_DETAILS;
--Calculate the total revenue generated.
SELECT ROUND(SUM(P.PRICE*OD.QUANTITY),2) AS TOTAL_REVENUE 
FROM ORDER_DETAILS OD
JOIN PIZZAS P
ON P.PIZZA_ID = OD.PIZZA_ID;
--5. Find the average order value.
SELECT ROUND(SUM(P.PRICE*OD.QUANTITY)/COUNT(DISTINCT OD.ORDER_ID),2) AS AVG_ORDER_VALUE
FROM ORDER_DETAILS OD
JOIN PIZZAS P
ON P.PIZZA_ID = OD.PIZZA_ID;
--6. Highest Priced Pizza.
SELECT P.P_SIZE ,P.PRICE , PT.NAME FROM PIZZAS P
JOIN PIZZA_TYPES PT
ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
ORDER BY P.PRICE DESC
LIMIT 1;
--7. Lowest Priced Pizza.
SELECT P.P_SIZE ,P.PRICE , PT.NAME FROM PIZZAS P
JOIN PIZZA_TYPES PT
ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
ORDER BY P.PRICE 
LIMIT 1;
--8. Number of Pizza Types.
SELECT COUNT(*) AS NO_OF_PIZZA_TYPES 
FROM PIZZA_TYPES;
--9. Pizzas in Each Category.
SELECT CATEGORY , COUNT(*) FROM PIZZA_TYPES
GROUP BY CATEGORY;
--10 Revenue by Category.
SELECT PT.CATEGORY , ROUND(SUM(P.PRICE*OD.QUANTITY),2) AS CATEGORY_REVENUE
FROM PIZZA_TYPES PT
JOIN PIZZAS P
ON PT.PIZZA_TYPE_ID = P.PIZZA_TYPE_ID
JOIN ORDER_DETAILS OD
ON P.PIZZA_ID = OD.PIZZA_ID
GROUP BY PT.CATEGORY
ORDER BY CATEGORY_REVENUE DESC;
--11. Revenue by Pizza Size.
SELECT P.P_SIZE , ROUND(SUM(P.PRICE*OD.QUANTITY),2) AS SIZE_REVENUE
FROM PIZZAS P
JOIN ORDER_DETAILS OD
ON P.PIZZA_ID = OD.PIZZA_ID 
GROUP BY P.P_SIZE
ORDER BY SIZE_REVENUE DESC;
--12. Top 10 Best Selling Pizzas.
SELECT PT.NAME , SUM(OD.QUANTITY) AS TOTAL_SOLD
FROM PIZZAS P
JOIN ORDER_DETAILS OD
ON P.PIZZA_ID = OD.PIZZA_ID
JOIN PIZZA_TYPES PT
ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
GROUP BY PT.NAME
ORDER BY TOTAL_SOLD DESC
LIMIT 10;
--13. Top 10 Revenue Generating Pizzas.
SELECT PT.NAME ,ROUND(SUM(P.PRICE*OD.QUANTITY),2)AS TOTAL_REVENUE
FROM PIZZAS P
JOIN ORDER_DETAILS OD
ON P.PIZZA_ID = OD.PIZZA_ID
JOIN PIZZA_TYPES PT
ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
GROUP BY PT.NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;
--14. Busiest Hour.
SELECT EXTRACT(HOUR FROM TIME) AS HOURS,
COUNT(*) AS TOTAL_ORDERS FROM ORDERS
GROUP BY HOURS
ORDER BY TOTAL_ORDERS DESC;
--15. Orders by Day.
SELECT TO_CHAR(DATE,'DAY') AS DAYS,
COUNT(*) AS TOTAL_ORDERS FROM ORDERS
GROUP BY DAYS
ORDER BY TOTAL_ORDERS DESC;
--16. Orders by Month.
SELECT TO_CHAR(DATE,'MONTH') AS MONTHS,
COUNT(*) AS TOTAL_ORDERS FROM ORDERS
GROUP BY MONTHS
ORDER BY TOTAL_ORDERS DESC;
--17. Top 5 Most Expensive Pizzas.
SELECT PT.NAME , P.P_SIZE, P.PRICE
FROM PIZZAS P
JOIN PIZZA_TYPES PT
ON P.PIZZA_TYPE_ID =PT.PIZZA_TYPE_ID
ORDER BY P.PRICE DESC
LIMIT 5;
--18. Top 5 Cheapest Pizzas.
SELECT PT.NAME , P.P_SIZE, P.PRICE
FROM PIZZAS P
JOIN PIZZA_TYPES PT
ON P.PIZZA_TYPE_ID =PT.PIZZA_TYPE_ID
ORDER BY P.PRICE 
LIMIT 5;
--19. Revenue by Month.
SELECT TO_CHAR(O.DATE,'MONTH') AS MONTHS,
ROUND(SUM(P.PRICE*OD.QUANTITY),2) AS REVENUE
FROM ORDERS O
JOIN ORDER_DETAILS OD
ON OD.ORDER_ID = O.ORDER_ID
JOIN PIZZAS P
ON P.PIZZA_ID = OD.PIZZA_ID
GROUP BY MONTHS 
ORDER BY REVENUE DESC;
--20. Revenue by Day.
SELECT TO_CHAR(O.DATE,'DAY') AS DAYS,
ROUND(SUM(P.PRICE*OD.QUANTITY),2) AS REVENUE
FROM ORDERS O
JOIN ORDER_DETAILS OD
ON OD.ORDER_ID = O.ORDER_ID
JOIN PIZZAS P
ON P.PIZZA_ID = OD.PIZZA_ID
GROUP BY DAYS ;
--21. Rank Pizzas by Revenue.
SELECT PT.NAME , ROUND(SUM(P.PRICE*OD.QUANTITY),2) AS REVENUE,
RANK()OVER(ORDER BY SUM(P.PRICE*OD.QUANTITY) DESC ) AS RANKING
FROM PIZZAS P
JOIN PIZZA_TYPES PT
ON P.PIZZA_TYPE_ID =PT.PIZZA_TYPE_ID
JOIN ORDER_DETAILS OD
ON P.PIZZA_ID = OD.PIZZA_ID
GROUP BY PT.NAME;
--22. Rank Categories by Revenue.
SELECT PT.CATEGORY , ROUND(SUM(P.PRICE*OD.QUANTITY),2) AS REVENUE,
RANK()OVER(ORDER BY SUM(P.PRICE*OD.QUANTITY) DESC ) AS RANKING
FROM PIZZAS P
JOIN PIZZA_TYPES PT
ON P.PIZZA_TYPE_ID =PT.PIZZA_TYPE_ID
JOIN ORDER_DETAILS OD
ON P.PIZZA_ID = OD.PIZZA_ID
GROUP BY PT.CATEGORY;
--23.  Monthly Revenue Trend.
SELECT DATE_TRUNC('MONTH',O.DATE)AS MONTH,
ROUND(SUM(P.PRICE*OD.QUANTITY),2) AS REVENUE
FROM ORDERS O
JOIN ORDER_DETAILS OD
ON O.ORDER_ID = OD.ORDER_ID
JOIN PIZZAS P
ON P.PIZZA_ID = OD.PIZZA_ID
GROUP BY MONTH
ORDER BY MONTH;
--24. Least Selling Pizza.
SELECT PT.NAME, SUM(OD.QUANTITY) AS SOLD_PIZZA
FROM PIZZA_TYPES PT
JOIN PIZZAS P
ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
JOIN ORDER_DETAILS OD
ON P.PIZZA_ID = OD.PIZZA_ID
GROUP BY PT.NAME 
ORDER BY SOLD_PIZZA 
LIMIT 1;
--25. Create Monthly Sales View.
CREATE VIEW MONTHLY_SALES AS
SELECT DATE_TRUNC('MONTH',O.DATE)AS MONTH,
ROUND(SUM(P.PRICE*OD.QUANTITY),2) AS REVENUE
FROM ORDERS O
JOIN ORDER_DETAILS OD
ON O.ORDER_ID = OD.ORDER_ID
JOIN PIZZAS P
ON P.PIZZA_ID = OD.PIZZA_ID
GROUP BY MONTH
ORDER BY MONTH;
--SHOW VIEW
SELECT * FROM MONTHLY_SALES 
LIMIT 10;
